### ISSUE TITLE
Write a py solution for problem:  Linked List Cycle

### ISSUE THREAD

**Issue by Nerdcode** [Nerdcode/Leetcode-Grind75#27]
https://leetcode.com/problems/linked-list-cycle/

please do write explanation

**Comment by harshita1611** [comment]
I have created pr for this problem , please review and let me know the changes

**Comment by Nerdcode** [comment]
linking this issue with the PR

**Comment by Nerdcode** [comment]
next time. create a branch and then push. instead of commiting in main.
