### ISSUE TITLE
Write a py solution for problem: implement Queue using Stacks

### ISSUE THREAD

**Issue by Nerdcode** [Nerdcode/Leetcode-Grind75#28]
https://leetcode.com/problems/linked-list-cycle/
pls do submit explanation

**Comment by Ash0069** [comment]
wrong link i guess

**Comment by 0xScratch** [comment]
@Ash0069 You are right man!
Here's the correct one -> https://leetcode.com/problems/implement-queue-using-stacks/

**Comment by dynamicdhxx** [comment]
Heyy!
I would like to work on this issue to brush up my DSA concepts. Kindly assign me this issue 😊.
