### ISSUE TITLE
Write a solution for Problem : Best Time to Buy and Sell Stock in Python

### ISSUE THREAD

**Issue by Nerdcode** [Nerdcode/Leetcode-Grind75#5]
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

**Comment by harshita1611** [comment]
Hi, I have already solved this question, you may check on my leetcode profile i.e. harshita__016__ , Can you please assign this issue to me?

**Comment by Ash0069** [comment]
Please assign this issue to me

**Comment by Nerdcode** [comment]
@harshita1611 @Samihan15 will be raising other issues. pls contribute. closing this one,
